### PR TITLE
Merge/ds

### PR DESCRIPTION
**Pull request by kamwoods**
Merge bitcurator-cli code from @digitalsleuth, retaining commit history. Code originally posted at https://github.com/digitalsleuth/bitcurator-cli.

### CODE REVIEW

**Comment by digitalsleuth** [comment]
Hey @kamwoods Just had a chance to take a look, and there are a couple of changes that will need to be made. The pointers for the repo, your Public PGP key will need to replace mine in the bitcurator-cli.js, and the support for Jammy will need to be added. I am going to do that now, but will remove my PGP key, so the cli tool should be ready for your key as soon as I'm done.

**Comment by digitalsleuth** [comment]
Done. With the addition of the PGP key in the bitcurator-cli.js file, and the 8 character signing key in the package.json, this should be ready for a build and test. You will need to pull those changes over first, then build a release from the bitcurator-salt repo, and you should be ready!

**Comment by kamwoods** [comment]
Thanks @digitalsleuth , much appreciated. Did a test build locally with our key without issue - and again, thank you for the build doc, a huge help. Merging now, and will get to the environment release soon (there are a few additional state changes I'll need to make before asking others in the BC group to test).

**Comment by digitalsleuth** [comment]
Glad to hear and happy to help!

**Pull request merged**
